INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (1, 'Dr. Wolf H. Fahrenbach', 'Senior Investigator', 'Cryptozoology Society');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (2, 'Stan Courtney', 'Lead Investigator', 'Cryptid Investigation Bureau');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (3, 'Charles Lamica', 'Senior Investigator', 'Wildlife Research Institute');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (4, 'Kevin Withers', 'Chief Investigator', 'Cryptozoology Society');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (5, 'John Salmond', 'Research Investigator', 'Sighting Documentation Center');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (6, 'Conor Ameigh', 'Senior Investigator', 'BFRO');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (7, 'Joanna Cuva', 'Junior Investigator', 'BFRO');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (8, 'Mary Ross', 'Chief Investigator', 'BFRO');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (9, 'Kevin Smykal', 'Junior Investigator', 'Cryptid Investigation Bureau');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (10, 'W. Gibson', 'Junior Investigator', 'Cryptozoology Society');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (11, 'Steve Phillips', 'Research Investigator', 'Wildlife Research Institute');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (12, 'Michael  Brumfield', 'Research Investigator', 'BFRO');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (13, 'Morris Collins', 'Field Investigator', 'Wildlife Research Institute');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (14, 'Matthew Moneymaker', 'Lead Investigator', 'Wildlife Research Institute');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (15, 'Thomas Bruns', 'Chief Investigator', 'Sighting Documentation Center');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (16, 'R. Monteith', 'Junior Investigator', 'Sighting Documentation Center');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (17, 'Vince Lauria', 'Chief Investigator', 'Cryptid Investigation Bureau');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (18, 'Mick Minnis', 'Research Investigator', 'Bigfoot Field Research');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (19, 'Tal H. Branco', 'Field Investigator', 'BFRO');
INSERT INTO INVESTIGATOR (Investigator_ID, Investigator_Name, Title, Organization) VALUES (20, 'Brad Sasser', 'Lead Investigator', 'Bigfoot Field Research');
