INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Legendary Bigfoot sighted near Kasigluk', '2013-01-23', 'By KJ Lincoln', 1);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Bigfoot sightings of years past draw some interest now', '2004-07-11', 'T', 2);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Bigfoot Legend Thrives In Chilton County: Man-Like Creature Lives In Peach Grove, According To Legend', '2004-07-08', 'N', 3);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Bigfoot sighting reaching Silver milestone', '2004-07-08', 'By Jason Cannon', 4);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Strange creature sighted near Sepulga River in Conecuh County, Alabama', '2016-07-28', 'By Lee Peacock', 5);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'The Fouke Monster 30 Years Later: Ex-journalists recall sifting fact from Fouke fiction after sighting', '2001-06-24', 'By Sunni Thibodeau', 6);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'The Fouke Monster: A look at how the media recorded the reports of the 1971 alleged sighting of a large creature in rural Miller County, Ark.', '2001-06-24', 'By Staff Writer  ', 7);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Bigfoot Sighting Reported in California', '2017-10-13', 'By Alexandra Lehnert', 8);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'He''s big! He''s bashful! He smells bad!', '1971-08-30', 'By Pat Putnam', 9);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'The Legend of the Skunk Ape', '2014-05-24', 'By Anna  Carabeo', 10);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Creature Feature', '1998-02-19', 'By Jim Kelly', 11);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'The Monster of Two Egg, Florida?', '2010-02-23', 'By Dale Cox', 12);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Woman claims Bigfoot is real, and is in the Goethe State Forest', '2014-03-23', 'By Bruce  Ackerman', 13);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Waiting for Skunk Ape to Surface Again', '1975-11-19', 'By Marilyn Alva', 14);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'The Skunk Ape of Florida', '2007-10-28', 'By Cinnamon Bair', 15);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', '"Ape" Sighting Draws Interest', '2004-12-29', 'By Gary White', 16);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', '[Our Own Loch Ness Monster?  Woman''s Sighting of Ape-Like Green Swamp Creature Among the Theories Studied by Cryptozoologists]', '2004-11-13', 'By Gary White', 17);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Skunk Ape Sighting in Myakka', '2013-06-06', 'H', 18);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'Return of the Mole Man', '2012-11-01', 'T', 19);
INSERT INTO REPORT (Report_Type, Headline, Submitted_Date, Author, Source_ID) VALUES ('Media Article', 'In Search of the Skunk Ape', '2010-05-02', 'By Dean  Poling', 20);
